name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo6 \
          cmake \
          libffi-dev \
          libssl-dev \
          automake \
          autopoint \
          gettext \
          python3-pip \
          python3-virtualenv \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade cython==0.29.33
        pip install buildozer
        pip install cryptography
    
    - name: Run encryption tests
      run: |
        python test_encryption_standalone.py
    
    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaultnote-apk
        path: bin/*.apk
        retention-days: 30
