name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK with Kivy Docker
      run: |
        docker run --rm \
          -v "$PWD":/workdir \
          -w /workdir \
          kivy/buildozer:master \
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vaultnote-apk
        path: bin/*.apk
